services:
  - type: web
    name: ayraservices
    env: python
    region: oregon
    plan: free
    buildCommand: ./build.sh
    buildCommand: pip install -r requirements.txt && python add_phone_verified.py
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ayraservices-db
          property: connectionString

databases:
  - name: ayraservices-db
    databaseName: ayraservices
    user: ayraservices
    plan: free
